version: '3'

services:
  web:
    image: nginx:${NGINX_VERSION}-alpine
    ports:
      - 8000:80
      - 3000:443
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html
    env_file:
      - .envs/nginx.env
    restart: unless-stopped
    depends_on:
      - php
      - mysqldb

  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    restart: unless-stopped
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./web:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    env_file:
      - .envs/php.env
      - .envs/mysqldb.env
    environment:
      - PMA_HOST=${MYSQL_HOST}
    restart: unless-stopped
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    ports:
      - 8989:3306
    volumes:
      - ./data/db/mysql:/var/lib/mysql
    env_file:
      - .envs/mysqldb.env
    restart: unless-stopped

  composer:
    image: composer:${COMPOSER_VERSION}
    command: install
    volumes:
      - ./web/app:/app
